### ISSUE TITLE
New Argument Passing Syntax Doesn't Support List-style Objects

### ISSUE THREAD

**Issue by Zalarian** [Hillcrest-R-D/FORM#24]
I've recently discovered that a common pattern 

```fs
let ids = [ 1; 2; 3 ]
Orm.selectWhere state None ( """id in (:1)""", [ ids ] )
```

Is not supported. Unfortunately, to address this, we're going to have to allow any object to be passed in and match on the reflected type. Slow, but the only way to support this pattern... which needs to be supported.

Also, while I want to ensure speed and use arrays, forcing it on the user can be cumbersome. Let's genericise the type to a seq and let the user decide.

**Comment by mflibby** [comment]
resolved by #25
